
export const SuperCars = [
  {
      manufacturer: 'Hennessey',
      name: 'Venom F5',
      power: 1622,
      weight: 1338,
      acceleration: 2.0,
  },
  {
    manufacturer: 'Koenigsegg',
    name: 'Regera',
    power: 1500,
    weight: 1628,
    acceleration: 2.8,
  },
  {
    manufacturer: 'Bugatti',
    name: 'Chiron',
    power: 1500,
    weight: 1996,
    acceleration: 2.4,
  },
  {
    manufacturer: 'SSC',
    name: 'Tuatara',
    power: 1350,
    weight: 1247,
    acceleration: 2.5,
  },
  {
    manufacturer: 'Zenvo',
    name: 'ST1',
    power: 1104,
    weight: 1688,
    acceleration: 3.0,
  },
  {
    manufacturer: 'Aston Martin',
    name: ' Valkyrie',
    power: 1013,
    weight: 1030,
    acceleration: 0,
  },
  {
    manufacturer: 'Ferarri',
    name: 'La Ferarri',
    power: 963,
    weight: 1255,
    acceleration: 2.5,
  },
  {
    manufacturer: 'McLaren',
    name: 'P1',
    power: 916,
    weight: 1395,
    acceleration: 2.8,
  },
  {
    manufacturer: 'Dodge',
    name: 'Challenger SRT Demon',
    power: 852,
    weight: 1930,
    acceleration: 2.3,
  },
  {
    manufacturer: 'Lamborghini',
    name: 'Centenario',
    power: 770,
    weight: 1520,
    acceleration: 2.8,
  },
  {
    manufacturer: 'Porsche',
    name: '918 Spyder',
    power: 767,
    weight: 1490,
    acceleration: 2.8,
  },
  {
    manufacturer: 'Chevrolet',
    name: 'Corvette ZR1',
    power: 766,
    weight: 1615,
    acceleration: 3.0,
  },
  {
    manufacturer: 'Saleen',
    name: 'S7 Twin Turbo',
    power: 760,
    weight: 1300,
    acceleration: 2.8,
  },
  {
    manufacturer: 'Pagani',
    name: 'Huayra BC',
    power: 745,
    weight: 1350,
    acceleration: 2.7,
  },
  {
    manufacturer: 'Nissan',
    name: 'GT-R Nismo',
    power: 600,
    weight: 1710,
    acceleration: 2.7,
  },
];